### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by MuscleRumble** [cryptomator/cryptomator-ios#1]
Add WebDAV support to enable ownCloud and many other cloud storage services based on the WebDAV protocol.

**Comment by gstammw** [comment]
I really second that.

**Comment by Allibabba** [comment]
Hi,

ich nutze die Desktop-Version über Mac- und Windowsgrenzen hinweg und bin damit äußerst zufrieden :-)
Eben habe ich die IOS App gekauft und dann festgestellt, dass ich damit nicht an meine ownCloud-Instanz herankomme. Das ist echt schade.
Ich würde es daher ebenfalls sehr begrüßen, wenn die App eine webDAV Funktionalität bekommen würde.

Wann kann man ungefähr mit einer Realisierung rechnen?

Cheers,
Ralf

**Comment by MuscleRumble** [comment]
Hey Ralf, WebDAV wird definitiv die nächste Cloud-Integration, die wir in der iOS-App unterstützen wollen! Zwischenzeitlich wird zwar noch ein Update kommen, um die iCloud-Integration zu verbessern (wir haben damit noch einige Schwierigkeiten), daher wird das nächste Update erst einmal noch Fehlerbehebungen beinhalten, aber unmittelbar danach ist dann die WebDAV-Integration dran! Eine genau Timeline kann ich dir zum jetzigen Zeitpunkt aber nicht nennen.

-

WebDAV integration will be the next cloud storage service that we would like to support. But first we're going to fix some bugs with the next update, especially improve iCloud integration. We don't have a timeline yet for WebDAV support, but it definitely has the highest priority for our next minor update!

**Comment by clausthaler** [comment]
Servus,

möchte mich Allibabba anschließen. War gerade dabei meine Ordner von Boxcryptor zu migrieren, um dann nach dem Kauf der IOS App festzustellen, dass der OwnCloud-Zugriff nicht funktioniert. Die Referenz auf eurer Startseite, in der OwnCloud erwähnt wird, scheint ein Android-User zu sein. Schade.

Gruß
Ralf

**Comment by MuscleRumble** [comment]
Wir werden versuchen, die Entwicklung von Version 1.1 bis Ende diesen Monats fertigzustellen. Danach folgt eine kurze Testphase und der Review-Prozess durch Apple, daher dürfte einer Veröffentlichung im App Store am Anfang Mai nichts im Wege stehen!

Zur Info: Die Referenz auf unserer Website bezog sich auf die Desktop-App. Sorry, dass es dadurch irreführend war! Eine Android-App haben wir noch gar nicht. 😉

---

Small update on our roadmap: We'll try to finish development of version 1.1 until the end of this month. We're also going to have a short test phase and after that there might be a slight delay due to the review process by Apple. All in all, an App Store release is very likely to happen in the beginning of May!

Stay tuned! 👍

**Comment by MuscleRumble** [comment]
Development is finished! We're going to give it some more time for testing (still waiting for TestFlight's Beta App Review though). I'll work on the other issues of milestone 1.1 in the meantime. "Beginning" of May was a little optimistic, but we're getting there soon. 😉

**Comment by MuscleRumble** [comment]
Thanks to the testers, some bugs were detected that had to be fixed. :grin: But all in all it looks good now. I'm going to submit the app for review tonight or tomorrow at the latest.
