### ISSUE TITLE
Face ID Support

### ISSUE THREAD

**Issue by owetterau** [cryptomator/cryptomator-ios#101]
## Basic Info
I'm using iOS in version: 11.1 / iPhone X
I'm running Cryptomator in version: 1.2.6

## Description
Please support Face ID. At the moment, only Touch ID is supported which obviously does not work with iPhone X.

**Comment by tobihagemann** [comment]
Yes. :+1:

In the meantime, you can just say "Allow" when it asks you if you'd like to use Face ID instead of Touch ID.

**Comment by tobihagemann** [comment]
Fixed in 1.3.0
