### ISSUE TITLE
Preview any file as plain text

### ISSUE THREAD

**Issue by yixunx** [cryptomator/cryptomator-ios#105]
I have a .md file in my vault, and the iOS app does not display the content of the file unless I change its extension to .txt. An "open as plaintext" option can be useful.

**Comment by Eyremba** [comment]
> I have a .md file in my vault, and the iOS app does not display the content of the file unless I change its extension to .txt.

Yes, I have the same issue with ".java" files.

**Comment by Eyremba** [comment]
Please add this feature...
