### ISSUE TITLE
Search bar partly hidden when sharing files into cryptomator

### ISSUE THREAD

**Issue by StanoRiga** [cryptomator/cryptomator-ios#106]
## Basic Info

I'm using iOS in version: 11.3.0
I'm running Cryptomator in version: 1.3.1 (549)  

## Description
If you want to store a file in cryptomator via the share file fuction, and the cursor is placed into the search bar, the search bar is partly hidden (yellow frame in screenshot). I assume it’s because of the “choose location” dialogue iOS is adding (red frame in screenshot).

To reproduce:
1) Open photo ap
2) Click “Share”
3) select photo
4) click “next” and select “save in cryptomator”
5) click “select folder”
6) select and open vault
7) When you see the root of your open vault, swipe down to show search bar
8) Place cursor in search Field and watch it disappear
![9990fb4b-26a5-4732-8e12-f17376316b57](https://user-images.githubusercontent.com/30843029/40503515-9a187d16-5f8e-11e8-8dfc-49d203e73fb6.jpeg)

**Comment by tobihagemann** [comment]
Bug confirmed and fix found. Will be part of 1.3.2 release.
