### ISSUE TITLE
iOS Files Integration apparently broken

### ISSUE THREAD

**Issue by luclu** [cryptomator/cryptomator-ios#107]
## Basic Info

iOS version: 11.3.1
Cryptomator: 1.3.1

## Description

Tapping the Cryptomator integration within the new iOS Files app will quickly highlight the iCloud list item, invoke a loading screen and finally fall back to the main screen:

![img_0210 trim mov](https://user-images.githubusercontent.com/10135872/40746139-e28fff04-6459-11e8-8c79-be051cc99b80.gif)

I was able to replicate this behaviour on an iPhone X as well as a iPad Pro (both iOS 11.3.1).
Furthermore I removed the app on all devices, removed the Cryptomator iCloud folder via iCloud's "manage storage" feature.

Eventually I even waited several days after setting the apps up in case that weird iCloud bug from the FAQ should trigger.

**Comment by StanoRiga** [comment]
Dublicate to #98
