### ISSUE TITLE
App gets stuck in file preview, when backgrounding the app with auto-lock instant, and then re-opening

### ISSUE THREAD

**Issue by babymastodon** [cryptomator/cryptomator-ios#112]
## Issue Checklist

Before creating a new issue make sure that you
- searched existing (and closed) issues: https://github.com/cryptomator/cryptomator-ios/issues
- searched the knowledge base: https://community.cryptomator.org/c/kb
- have read the support guide: https://github.com/cryptomator/cryptomator-ios/blob/master/SUPPORT.md
- have read the contribution guide: https://github.com/cryptomator/cryptomator-ios/blob/master/CONTRIBUTING.md
- have read the Code of Conduct: https://github.com/cryptomator/cryptomator-ios/blob/master/CODE_OF_CONDUCT.md

## Basic Info

I'm using iOS in version: 12.1.4

I'm running Cryptomator in version: 1.3.8 (601)

## Description

Enable Auto-lock = Instant (settings -> Auto-Lock)
Open a file (eg. txt or pdf) in the vault
Click the <-> in the top left, to expand the file preview to fill the entire screen.
Background the app, by pressing the IPad Home button.
Re-open the app by clicking the cryptomator icon on the IOS home page.
Expected result: Cryptomator should have auto-locked all of the vaults, and navigated back to the main page, showing the list of locked vaults.
Actual result: Cryptomator is stuck in the file preview page, with no file showing, and no way to navigate back to the list of vaults.

**Comment by tobihagemann** [comment]
Thank you for reporting the issue! Will be fixed in the next update.
