### ISSUE TITLE
OneDrive business-University doesn't redirect to organization sign-in page

### ISSUE THREAD

**Issue by Giggiux** [cryptomator/cryptomator-ios#113]
## Basic Info

I'm using iOS in version: 12.2

I'm running Cryptomator in version: 1.3.8

## Description

I just bought Cryptomator for iOS, opened it, clicked "Create new vault", "OneDrive",  then I tried to login with my university account (since I have 1tb free), automatically Microsoft tries to redirect me on "my organization's sign-in page", but it's stuck on the "loading" of this redirect.

It doesn't give me any error (I left it there loading for something like 3/4 minutes, and nothing).

Tried to login with the OneDrive app and didn't get any problem.

The organization's url is `usi.ch`.

Regards
:)

**Comment by Steareth-4** [comment]
I've run into the same problem. Login to OneDrive (app) works like a charm. I'm getting stuck in Cryptomator on the "Taking you to your organization's sign-in" page.

Cryptomator 1.3.8
IOS 12.2 on iPhone 6s Plus

**Comment by Steareth-4** [comment]
Dear @Giggiux 

Try logging in while not using Eduroam or VPN. Shutting off the iPhones Wi-Fi connection during the login procedure did the trick for me.
