### ISSUE TITLE
Renaming plaintext file name (from long to short) breaks corresponding ciphertext file name

### ISSUE THREAD

**Issue by buddydvd** [cryptomator/cryptomator-ios#114]
## Basic Info

I'm using iOS version 12.2.

I'm running Cryptomator version 1.3.8. 

## Description

The file rename (or move) operation contains a bug. When renaming a plaintext file name—from long to short—the new ciphertext version of the file name retains the `.lng` file extension.

Users of the iOS application doesn't experience the effect of this bug. Apparently, the application is able to ignore the error and include the incorrectly named file in directory listings.

Users of the Java-based version of Cryptomator do experience the effect of this bug. Affected files appear missing in the vault. The `cryptofs` library ignores malformed ciphertext file names.

## Steps to reproduce

1. Create an empty vault in Google Drive
2. Save a file into this vault and give it a long file name (e.g., `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.pdf`).
3. Rename the file in step 2 into a short file name (e.g., `xxxxxxxxxxxxxxxxxxxxxx.pdf`).
4. Check the Google Drive vault's `/d/...` folder containing the ciphertext file.

## Expected

We should find a file ciphertext file name without file extension. For example, `CSUICHTHFHIB5QJNIHDPBWMSXBTVJOTX5NACP2AWTN2GF6OOR6OKS3EAB3XO7XQ===`.

## Actual

We find a file with ciphertext file name with `.lng` extension. For example, `CSUICHTHFHIB5QJNIHDPBWMSXBTVJOTX5NACP2AWTN2GF6OOR6OKS3EAB3XO7XQ===.lng`.

**Note the `.lng` file extension on the non-deflated ciphertext file name!**

**Comment by buddydvd** [comment]
**An alternative title:** Renaming files on iOS make them disappear on Desktop.

**Comment by tobihagemann** [comment]
Core issue actually lies in Google Drive itself, see https://github.com/cryptomator/cryptomator/issues/891
