### ISSUE TITLE
Unable to unlock volumes on iOS 13 Beta

### ISSUE THREAD

**Issue by ajgraves** [cryptomator/cryptomator-ios#115]
### Description

Cryptomator is unable to unlock volumes on iOS or iPadOS 13 Betas.

### System Setup

* Operating system and version: iOS 13 / iPadOS 13 Public Beta 4
* Cryptomator version: 1.4.0 (630)
* Drive: All

### Steps to Reproduce

1. Launch Cryptomator
2. Select a volume to unlock
3. Small dialog shows "unlocking" and spinning circle. Nothing happens.

#### Expected Behavior

Volumes should get unlocked and mounted.

#### Actual Behavior

Volume never gets unlocked.

#### Reproducibility

Every time.

### Additional Information

Logs were sent via email from the option within the app. Unfortunately since I force closed the app as it was unable to be used in any way while waiting to unlock the volume, the log has only two entries showing the app stopping and starting again.

**Comment by das-schaf** [comment]
Same behaviour with iOS 13.1.2

**Comment by tobihagemann** [comment]
Not sure if issues reported by @ajgraves and @das-schaf are related. I'm quite sure that the original report was indeed "just" a iCloud Drive bug in the iOS beta that Apple has fixed.

@ajgraves Are you still experiencing this issue?

@das-schaf What device are you using (iPhone/iPad)? Which cloud storage are you using? If you're using iPhone and iCloud Drive, could you please check the iOS settings under "Cellular" if you have "iCloud Drive" activated (it's at the bottom, below "Wi-Fi Assist")?

**Comment by das-schaf** [comment]
@tobihagemann My cloud storage is OneDrive. Opening the vault with Cryptomator for Windows works flawlessly. Opening on my iPhone results in an endless "unlocking" progress indicator.

**Comment by tobihagemann** [comment]
@das-schaf Could you please try to sign out and log back to OneDrive inside Cryptomator? You can do that at the gear icon at the top right and then under "Cloud Services". It's probably related to: https://community.cryptomator.org/t/ios-onedrive-connection-broken-authentication-fails-browser-not-allowed/4190/6

We're working on a fix for the next update.

**Comment by das-schaf** [comment]
@tobihagemann That did the trick. Thanks!

**Comment by ajgraves** [comment]
Seems to be working for me

**Comment by tobihagemann** [comment]
All right! :+1:
