### ISSUE TITLE
Visually indicate files that are cached

### ISSUE THREAD

**Issue by IgiMar** [cryptomator/cryptomator-ios#117]
Hello,
I think it would be useful that files that are available for offline use (are cached) may be made recognisable as that at UI level. For example: changing the color of the button that opens them or whichever other marks.
Surely a ‘real’ ‘’offline option”, both at file level and folder level, like would be more than welcome so that file gets synchronised automatically whenever possible.

**Comment by tobihagemann** [comment]
Duplicate of #44 and #45

**Comment by IgiMar** [comment]
@tobihagemann, I doesn’t seems to me that my suggestion is a duplicate of #44 and #45 AT ALL.
You completely skipped the suggestion and quickly jumped to the last phrase that was an ‘eventual’ corollary of my suggestion. I try to explain better and slowly:
A) we all know how that the actual implementation of offline file handling works in Cryptomator for iOS: accessed files get cached. Otherwise not. Right? 
B) While opening a Vault, the main directory is listed so that that the only things a user sees are folder names and file names.
C) There is no way to know, at User Interface Level, to know if a file is actually cached or not. 
D) MY SUGGESTION WAS: why not to show on the UI if a file is cached or not? For example, changing the color of the button on the left?
E) Why could it be useful? If it’s not obvious, imagine a scenario when files are sent from a desktop to an iPad/iPhone to be used eventually offline. Potentially to another person. How can one be sure to have the needed files cached? If one doesn’t know or doesn’t remember which the files were or if the cache got cleared: tapping on them one by one while online. If the list is long it’s a waste of time and energy. Not really smart.
After my suggestion: one may just tap on the files tat ARE SHOWN to NOT be cached.

I dared to suggest something because:

1) I knew it wasn’t something involving ‘changes’ in the core code but just a minimal effort on the User Interface:

- for f in listed files:
     If f is cached
           button.color = yellow 
     Else
           button.color = white
     End if 
  Next f

That’s it.

2) I know, as a developer, that sometimes it is helpful to listen to users. It happens to me to get trapped in my own ideas and ways of seeing things. I gave my suggestion thinking to the people who helped me see. But if you’re not interested in this kind of feedback but just bug reports, just let me know.
I would add, that my suggestion would not be essential anyway because it would address just one of the MANY drawbacks of a syncing for offline file handling that is not automatic.

All the best

**Comment by tobihagemann** [comment]
Thank you for elaborating your original feature request. I'm still not convinced yet on both "if" this problem actually applies to the current caching mechanism and "how" to actually solve this without misleading the user of what the caching actually does.

Caching is mostly something that is transparent and invisible to the user. The purpose of this cache in particular is to avoid repeated downloading and _not_ a guarantee that it represents the most up-to-date data. It's just a happy accident that this caching is a workaround for the actual offline functionality (#44 and #45).

E.g., it's not comparable to iCloud Drive with the "cloud icon" or to Dropbox with the "phone icon" because that's actually what #44 and #45 are supposed to solve.

**Comment by IgiMar** [comment]
Thank you. 
It would more like OneDrive with a bit of courtesy. And, in any case, I can’t see how it would mislead if there is not an option to ADD ‘offline’ status and if the UI does NOT use icons whose meaning is known like the cloud with an arrow or the check inside a solid circle or whatever. That’s why I suggested, but that was just an example, a small change of color of an element already present. A different thing. 
In general I’m dubious about UI having precedence over functionality: by definition it should be the contrary. Anyway: if offline file handling is a ‘workaround’, then it’s better than nothing. Making it less ‘workaround’ would be more appreciated. Especially considering that #45 is more than one year ago and the offline issue doesn’t seem to have big priority.
In my opinion it should.
  
All the best

**Comment by IgiMar** [comment]
P.S. anyway, without that ‘workaround’ I personally would have not considered Cryptomator useful and worthy to be investigated for professional use.
