### ISSUE TITLE
multi upload file name bug

### ISSUE THREAD

**Issue by forestmaster** [cryptomator/cryptomator-ios#123]
### Description

When uploading several files at once e.g. by selecting several fotos from an album and then trying to save them in cryptomator there is a naming conflict if the fotos have been taken in a ahort time and have the same name. 
I consider it as a bug  because in every software users are used to see a dialogue asking how to handle the naming problem. Simplest solution would be just append numbers to the filenames. 

### System Setup

* Operating system and version:
all iOs versions.

* Cryptomator version: all versions

### Steps to Reproduce

Select several fotos from Fotos app which have been taken in a short time and consequently have the same filename.

Try to share and save to cryptomator

-> error occurs

#### Expected Behavior

Cryptomator should just append increasing numbers to the files with the same filename
or at least offer that solution!

#### Actual Behavior

It’s necessary to rename every single file to have unique names. 

#### Reproducibility

always

**Comment by overheadhunter** [comment]
@tobihagemann Is this a regression? Has already been reported in (supposedly fixed) issue #78.

**Comment by forestmaster** [comment]
no, the bug still exists in the newest version of the iOS cryptomator app...
The old report dates back to 2017 but the bug still exists.
thx
best regards

**Comment by forestmaster** [comment]
Still nothing going on about solving this issue? 
I am still experiencing trouble with the renaming problem! 
Please developpers, have a look.

**Comment by StanoRiga** [comment]
> @tobihagemann Is this a regression? Has already been reported in (supposedly fixed) issue #78.

I can confirm that in former Version 1.2.6 the file name was bound to the timestamp of photo capturing date ([board post](https://community.cryptomator.org/t/edit-filename-pattern-for-image-upload/372)).
Now with Version 1.5.0 it is bound to the upload date, which leeds to the described bug (and imho does not make sense

**Comment by tobihagemann** [comment]
Bug fix can already be tested via TestFlight: https://testflight.apple.com/join/w91xUvMq

Will be soon released in version 1.5.1.
