### ISSUE TITLE
File modification date incorrect

### ISSUE THREAD

**Issue by jomey** [cryptomator/cryptomator-ios#126]
## Basic Info
Version: 1.5.0 (718)

## Description
File modification dates do not match the between the Mac OS Desktop client and the iOS.
In my case, the iOS App shows the vault creation date instead. 

## Steps
1. Create a new vault with the desktop app (Mac OS)
2. Copy an existing “older” document into there
3. Open the iOS app, add the new vault
-> The date underneath the file says modified on the date of vault creation

**Comment by tobihagemann** [comment]
I was able to reproduce the issue on Dropbox. Could you please let me know if you experienced this issue other than on Dropbox?

**Comment by jomey** [comment]
Yes, this is the setup I have and my vaults are on Dropbox. Have not seen this issue on other clients.

**Comment by tobihagemann** [comment]
Bug fix can already be tested via TestFlight: https://testflight.apple.com/join/w91xUvMq

Will be soon released in version 1.5.1.

**Comment by jomey** [comment]
Thank you, will give it a whirl ...

**Comment by jomey** [comment]
FYI - I also have the same setup when reporting #127
