### ISSUE TITLE
Onedrive AccessDenied when unlocking vault

### ISSUE THREAD

**Issue by oripka** [cryptomator/cryptomator-ios#134]
### Device Info
Cryptomator 1.5.1 (732)
iOS 14.2
iPhone

### Description

I am getting sporadic „accessDenied“ errors since yesterday on two different vaults on OneDrive. I tested on an iPad and iPhone.

Unlocking the same vaults from Windows and macOS works without errors. 

### Log

`Unlocking vault failed: Error Domain=SETOOneDriveDirectoryBrowserErrorDomain Code=1 "Unerwarteter Fehler. (Access denied, Code: accessDenied)" UserInfo={NSLocalizedDescription=Unerwarteter Fehler. (Access denied, Code: accessDenied)}`

**Comment by tobihagemann** [comment]
I was unable to reproduce the issue, OneDrive still seems to work fine here.

- Is this a personal OneDrive account or OneDrive for Business?
- What do you mean by "sporadic"? Does it mean that it sometimes work?
- Did you already try to sign out and log back into OneDrive? Via Cryptomator settings under "Cloud Services".

**Comment by oripka** [comment]
It is a business account. Sporadic means it works sometimes and sometimes not. I will try logout and login again tomorrow.

**Comment by oripka** [comment]
I logged out and back in and the error came up again but then after using the app for a while (also locking and unlocking the vault) it now seems to work again. Maybe a token renewal issue...

Thanks for the help
