### ISSUE TITLE
View next/previous document/picture by swiping 

### ISSUE THREAD

**Issue by brahimcha-ai** [cryptomator/cryptomator-ios#135]
### Summary

When in a folder, to move to the next or previous document, support swiping left, right in the iPhone screen

### Motivation

For stored picture I find myself all the time swiping left and right. It’s so natural to support this way of navigating 

### Considered Alternatives

Well right now I have to go back to folder and click on the new item

### Additional Context

Mainly useful for picture navigation

**Comment by overheadhunter** [comment]
Duplicate of #12
