### ISSUE TITLE
Shared folder support on Google Drive vaults

### ISSUE THREAD

**Issue by FrankelJb** [cryptomator/cryptomator-ios#136]
## Basic Info

I'm using iOS in version: 14.2.1

I'm running Cryptomator in version: 1.5.1

## Description

I have created a vault on Google Drive and I have shared the folder containing the `masterkey.cryptomator`. However, when trying to add the vault on Cryptomator I cannot find the shared folder to open. I have managed to sync the shared folder on desktop. I created a shortcut to the shared folder but it is not selectable.

**Comment by tobihagemann** [comment]
Here is a lengthy article on how Google ruined shared folder in Google Drive: https://www.androidpolice.com/2020/04/10/google-completely-ruined-shared-folders-in-drive/

At the end, the author presented a workaround:

> First, you can still move shared files and folders to your Drive, even on the web (no need for the Android app), but the option is hidden behind a keyboard shortcut. Go to your _Shared with me_ section, highlight the shared files or folders you want to move, and type _Shift+Z_ on your keyboard. You'll see the old move menu and can choose where to put those folders. On your PC, they'll sync and behave like they used to, no shortcut mess.

Does that work for you?
