### ISSUE TITLE
iOS Lockscreen and going back issue

### ISSUE THREAD

**Issue by Marcusg562** [cryptomator/cryptomator-ios#146]
### Description

1)
When I lock my phone during Cryptomator is opened the Cryptomator shows only grey and blue. No Tresors were shown anymore.

2)
When I transfer a file from Cryptomator to another Programm and go back, Then I can‘t do anything anymore and stuck in the preview

### System Setup

* Operating system and version: iOS 14.5 & iOS 14.5.1
* Cryptomator version: latest - 1.5.1(732)
* Volume type: Google Drive, ICloud Drive 

### Steps to Reproduce

1. See description

#### Expected Behavior

Cryptomator should still be usable as when I open it freshly

#### Actual Behavior

Cryptomator only usable after new start

#### Reproducibility

Always

**Comment by overheadhunter** [comment]
Unable to reproduce this. Can you share a screenshot of that "grey and blue" screen?

**Comment by Marcusg562** [comment]
See screenrecording (adding was not possible)

https://share.icloud.com/photos/0zoUSI4sIzxZBsM7seALqQhDA

**Comment by tobihagemann** [comment]
I really don't know how to reproduce this issue and don't understand how this is possible. 😕

**Comment by Marcusg562** [comment]
So, I close this issue because I was able to solve it. The reinstallation of the App fixed it. Perhaps there was something stuck in cache during the last update.
