### ISSUE TITLE
Shortcuts implementation

### ISSUE THREAD

**Issue by xplosionmind** [cryptomator/cryptomator-ios#160]
Add the possibility to upload files or entire folders with [Apple Shortcuts](https://apps.apple.com/us/app/shortcuts/id915249334) or add [x-callback-url](https://support.apple.com/guide/shortcuts/use-x-callback-url-apdcd7f20a6f/ios) support.

**Comment by tobihagemann** [comment]
We won't add this functionality to the "old" app anymore. But I'm more than open to add this to the "new" app, see https://github.com/cryptomator/ios/issues/56.

**Comment by xplosionmind** [comment]
Sorry, I missed it. Thanks a lot!
