### ISSUE TITLE
App freeze in certain conditions

### ISSUE THREAD

**Issue by paraduxos** [cryptomator/cryptomator-ios#164]
# Basic Info

I'm using iOS in version: 14.7.1

I'm running Cryptomator in version: 1.5.1 (732)

# Description

- Set Auto-lock: Instant
- Unlock vault
- Go into some folder in that vault
- Leave Cryptomator in background
- Go into the storage app of the vault
- Come back to Cryptomator

# Examples

- Auto-lock: Instant
- After unlock vault of Files or Google drive (or any stroage)
- Go into at least 1 step deeper folder (root folder working correctly)
- Leave Cryptomator in background
- Go into Files, Google drive app (or any storage) depends on which vault you just unlock
- Come back to Cryptomator

# Expected behavior

- Vault is locked
- Cryptomator working as usual

# Actual behavior

- Vault is not locked
- Cryptomator freezed. Locking vault or any other actions has no effect on cryptomator.

# Related issues

- [112](https://github.com/cryptomator/cryptomator-ios/issues/112)
- [89](https://github.com/cryptomator/cryptomator-ios/issues/89)

# Debug log files

`Your device is not configured for sending emails.`

I don't know how to fix this.

**Comment by paraduxos** [comment]
I just saw that there's also an new iOS app. Not sure if this has been fixed in the new app.

But I guess I would leave the issue here.

**Comment by tobihagemann** [comment]
Thank you for your bug report! There is definitely something wrong here, I will look into it.

Btw, the new app is indeed a _completely_ new app so both apps don't necessarily share the same bugs. :wink: This was the right repository to report the bug! :+1:

**Comment by tobihagemann** [comment]
Seems like an upstream bug in iOS 14, which has a workaround: https://stackoverflow.com/questions/63485966/question-about-ios-14-navigation-stack-management-different-from-ios-13/65711840#65711840

Fixed in the [latest TestFlight release](https://testflight.apple.com/join/w91xUvMq) and will be part of 1.6.0.
