### ISSUE TITLE
File Cache / Store local copy of downloaded files to avoid repeated downloading

### ISSUE THREAD

**Issue by NicolasCGN** [cryptomator/cryptomator-ios#17]
Does Cryptomator for iOS stores a local copy of a downloaded file from a vault?

I have the impression that a file is downloaded every time I click on it. No matter whether the file was already downloaded or not.

BitTorrent Sync stores a local copy of a downloaded file, provided that the time-stamp of the local file and the one in the remote vault are the same. Downloaded files are marked as such and the download process is shown with a progress bar.

**Comment by MuscleRumble** [comment]
You're right, the file gets downloaded every time wether you have downloaded it before or not. In an early beta version we actually had a file cache, but didn't have the time to implement it fully and correctly.

Thanks for your suggestion :+1:, we're collecting feature requests at the moment and we'll prioritize them next week, so stay tuned! :)

**Comment by tobihagemann** [comment]
Thanks to @ahelpingchip's issue #79, I'd like to add that this should be a persistent cache.

We could also be able to enable/disable this cache in the settings. Furthermore, settings like "cache size", "cache used", and "clear cache" could be added.

**Comment by lolo-14** [comment]
This would indeed be a great improvement !
