### ISSUE TITLE
Anlegen eines neuen Tresors nicht möglich (neustes IOS)

### ISSUE THREAD

**Issue by U2014** [cryptomator/cryptomator-ios#19]
![img_0834 3](https://cloud.githubusercontent.com/assets/18229228/14226237/8801eee8-f8dc-11e5-9a5c-ff3f5f016fb2.PNG)
Fehlermeldung siehe Anlage. Ist ein Bedienungsfehler oder was kann ich tun?
Danke

**Comment by MuscleRumble** [comment]
Hi, die Anlage fehlt leider, was genau sagt die Fehlermeldung? -Tobias

**Comment by MuscleRumble** [comment]
Könntest du bitte auf die Version 1.0.1 von Cryptomator aktualisieren und prüfen, ob es danach funktioniert?

**Comment by MuscleRumble** [comment]
Ach, ich habe mich verlesen... AuthenticationError steht da ja... ich denke mal, du hast es mit iCloud Drive probiert? Könntest du mal in die Einstellungen von iOS gehen, dann unter iCloud nachgucken, ob iCloud Drive aktiviert ist?

**Comment by U2014** [comment]
Super. Danke! Das war es.

**Comment by MuscleRumble** [comment]
Prima! :)
