### ISSUE TITLE
Cannot access shared folder, when I'm not the owner in OneDrive

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptomator-ios#29]
When someone else shares a folder with me, it's falsely shown as a file in the directory browser. That's why it's impossible to navigate inside a shared folder of which I'm not the owner.

**Comment by MuscleRumble** [comment]
I've discovered that OneDrive's API handles shared folders differently: https://github.com/OneDrive/onedrive-sdk-ios/issues/91

That's why I'll postpone this fix to the next patch (following 1.1). 😕

**Comment by MuscleRumble** [comment]
Update: Looks like our OneDrive implementation needs some reworking. Not sure if we have to switch to an ID-based (instead of path-based) approach completely, or only for shared folders.

**Comment by tobihagemann** [comment]
Fixed. Switched to an ID-based approach (almost identical to Google Drive). A mixed approach (IDs of shared folders (aka `remoteItem`) + remaining path) would've been technically possible. But it wouldn't have made much sense for uncached paths, because you don't know where the `remoteItem` begins.
