### ISSUE TITLE
blaucloud (WebDAV) Anmeldung nicht möglich

### ISSUE THREAD

**Issue by GreenDragon0505** [cryptomator/cryptomator-ios#34]
Hi 

Ich nutze den Cloud Speicher blaucloud und wollte mich Anmelden erhalte aber immer die Meldung 

Der Server scheint kein WebDAV-Sever zu sein

**Comment by MuscleRumble** [comment]
Ich habe auf Anhieb keine bessere Quelle gefunden: https://wiki.ubuntuusers.de/WebDAV/

Hast du diese URL für blaucloud probiert? `https://<user>.blaucloud.de/remote.php/webdav/`

**Comment by GreenDragon0505** [comment]
Danke hat funktioniert 

 https://<user>.blaucloud.de/

Hatte es wie oben angegeben ohne remote.php  und webdav
