### ISSUE TITLE
blaucloud Ordner und Dateien mit Sonderzeichen verschwinden

### ISSUE THREAD

**Issue by GreenDragon0505** [cryptomator/cryptomator-ios#36]
Hi :-) 

Ich habe einen Tresor namens Verschlüsselt und einen Ordner mit dem namen Bilder erstellt wenn ich in diesem wiederum Ordner erstelle und Bilder hochlade was auch ohne Probleme funktioniert und daraufhin wieder den Tresor Öffne sind die Ordner und die Bilder verschwunden erstelle ich die selben Ordner wieder bekomme ich den Hinweis sie existieren bereits habe auch Probiert die Bilder direkt in den Tresor hochzuladen das selbe Problem nichts bleibt erhalten

**Comment by MuscleRumble** [comment]
Hallo! Ich habe mir gerade einen blaucloud-Account erstellt und deinen Fall durchprobiert. Ich kann ihn bestätigen und habe festgestellt, dass es am Tresornamen "Verschlüsselt" liegt.

Es gibt einen Workaround: Wenn du die Zeile in der Tresorliste nach rechts wischst, kannst du den Tresor umbenennen. Scheinbar macht das "ü" noch Probleme. Benenn den Tresor bspw. in "Verschluesselt" um und du wirst deinen Bilder-Ordner usw. wieder sehen.

Wir werden den Fehler im nächsten Update beheben!

**Comment by MuscleRumble** [comment]
Fixed
