### ISSUE TITLE
Add pagination for directory listings

### ISSUE THREAD

**Issue by markuskreusch** [cryptomator/cryptomator-ios#37]
### Basic Info
GoogleDrive does not allow to retrieve all files in a directory at once but just a limited amount (100 default, up to 1000 possible). At the moment the iOS app does not display the full directory contents if the number of entries exeeds this number.

### Description

Some sort of pagination has to be implemented to allow loading of all directory entries from GoogleDrive.

**Comment by markuskreusch** [comment]
quick fixed by #38

**Comment by MuscleRumble** [comment]
I've look into the APIs and it looks like that this also applies to OneDrive. Apparently, the default page size is limited to 200.

**Comment by MuscleRumble** [comment]
There is a HUGE PROBLEM though. I don't know how to implement this properly. Encrypted and unencrypted files are obviously not alphabetically sorted in the same way. How should we support "infinite scrolling" and keep the sorting intact? 😕

**Comment by tobihagemann** [comment]
Fixed for Google Drive and OneDrive and implemented in the way as suggested (client-side, directory listing completely loaded before showing any results to the user). Wasn't necessary for iCloud Drive, Dropbox, and WebDAV.
