### ISSUE TITLE
Files from GoogleDrive missing when folder contains many files

### ISSUE THREAD

**Issue by markuskreusch** [cryptomator/cryptomator-ios#38]
### Basic Info

- Cryptomator Version 1.1.1

### Description

The iOS App displays only a specific amount of files in a GoogleDrive vault. Thus it is not possible to display all files in directories which contain more.

### Analysis

This is caused by a default paginiation limit of 100 when using the GoogleDrive API.

**Comment by MuscleRumble** [comment]
Temporarily fixed by increasing the page size limit to 1000. Will be fixed properly in #37.
