### ISSUE TITLE
iOS app can not handle apostrophe in vault names

### ISSUE THREAD

**Issue by markuskreusch** [cryptomator/cryptomator-ios#47]
### Basic Info

- I'm running Cryptomator on: all devices affected
- I'm using Cryptomator in version: 1.1.3

### Description

Some cloud providers can not handle an apostrophe (in a bug report U+0027 was mentioned, maybe also check [other variants](https://en.wikipedia.org/wiki/Apostrophe#Unicode)) in vault names and fail when adding such a vault, that has been created with the desktop application before.

This at least affects WebDav. Symptoms: Vaults with a ' are shown empty

**Workaround**
Rename the vault using the desktop application and remove the '.

**Comment by MuscleRumble** [comment]
It looks like I've already fixed that. 😄 I could reproduce this issue with the current App Store version, but couldn't anymore with the development version.

However, I've found an issue with Google Drive. Apparently, it's necessary to escape apostrophes explicitly. Going to fix that as well! 😅

**Comment by MuscleRumble** [comment]
Fixed
