### ISSUE TITLE
How to access notes within safe/tresor from other apps? (webdav?)

### ISSUE THREAD

**Issue by minthemiddle** [cryptomator/cryptomator-ios#51]
### Basic Info

- I'm running Cryptomator on: iPhone and Windows
- I'm using Cryptomator in version: 1.1.4

### Description

I would like to encrypt my synced notes with cryptomator and access them from a third-party app, such as [Notebooks 8](https://www.notebooksapp.com/) via WebDav as I can do on the Mac or Windows when using Cryptomator. However, I cannot find a Webdav address to copy and use. I tried `localhost:42427` with and without the following folder name but with no success

Also, I also tried to open the notes directly from a notes app such as [1Writer](http://1writerapp.com/) using the Dropbox folder, but that does not work either - rather obviously.

I can just access the notes from within Cryptomator - and just copy them to an app, but that is destroying the whole idea of a synced notes folder.

Any ideas or plans?

**Comment by MuscleRumble** [comment]
I'm not 100% sure, because I haven't used the apps you've mentioned. But this request could be related to #13, that's why I'll mark this as duplicate for the time being. There isn't a "more direct" way in the iOS ecosystem, because all apps are sandboxed.
