### ISSUE TITLE
OneDrive for Business support

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptomator-ios#6]
Add OneDrive for Business support. Should be possible with: https://github.com/OneDrive/onedrive-sdk-ios

**Comment by EndosMorph** [comment]
Hey, just want to ask if there are any updates on this topic?
Would be great to get this feature in one of the next versions.

**Comment by tobihagemann** [comment]
Unfortunately, we don't have any news on this. We're still very much focussed on the cloud storage services for consumers and consumer features in general.

**Comment by tobihagemann** [comment]
Fixed with 1.2.3 by switching to [MSGraphSDK](https://github.com/microsoftgraph/msgraph-sdk-ios)
