### ISSUE TITLE
Switch to Dropbox API v2

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptomator-ios#60]
Dropbox API v1 (currently used by Cryptomator) has been deprecated some months ago: https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

There's still some time though (until June 28, 2017). I've already acknowledged the deprecation when it was announced, but an Objective-C SDK for API v2 was missing back then: https://www.dropbox.com/developers/documentation/objective-c

At the time of writing, the website suggests that the SDK is still missing. But the new SDK is already available at: https://github.com/dropbox/dropbox-sdk-obj-c

It's fairly new and we'll take our time to adapt to the new API/SDK. Just wanted to say that I'm happy that Dropbox is working on an SDK for Objective-C, because I've read that you can't use the Swift SDK in an Objective-C project.

**Comment by felixkm** [comment]
This library might help you with that: https://github.com/CloudRail/cloudrail-si-ios-sdk
Supports Dropbox v2 API plus Google Drive, OneDrive and Box via the same API.

**Comment by tobihagemann** [comment]
Interesting! We've already optimized a lot in our app regarding cloud API access, so we probably won't switch to a new framework. But it's still nice to know about it for reference or future projects, thanks! :)

**Comment by felixkm** [comment]
Sounds good. Hope you have a chance to use it in some future projects. Grüße nach Bonn :)
