### ISSUE TITLE
Switch to Google Drive REST

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptomator-ios#67]
_From @vvoody on November 29, 2016 3:21_

### Basic Info

- I'm running Cryptomator on: iOS 10.1.1
- I'm using Cryptomator in version: 1.2.0

### Description

Hi, I think you need a plan for new authorization requests for adding Google Drive. https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html?m=1

_Copied from original issue: cryptomator/cryptomator#404_

**Comment by tobihagemann** [comment]
Thanks @vvoody! Didn't receive any info from Google that I have to update the authorization process. Good to know. :smile:

**Comment by vvoody** [comment]
Thank you very much :D
