### ISSUE TITLE
Camera Upload

### ISSUE THREAD

**Issue by vesparny** [cryptomator/cryptomator-ios#72]
### Basic Info

- I'm running Cryptomator on: iPhone
- I'm using Cryptomator in version: 1.2.0

### Description

Any chance to support a camera Upload feature?

**Comment by tobihagemann** [comment]
Hey! Do you mean #69?

**Comment by vesparny** [comment]
Nope,
I meant a feature that uploads any picture taken by the camera directly to the vault.
Something like the dropbox app does.

**Comment by tobihagemann** [comment]
Ah, understood! Then it's a duplicate of #20. :smile: Thank you for your suggestion!
