### ISSUE TITLE
Amazon Cloud Drive support

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptomator-ios#8]
Add Amazon Cloud Drive support. Should be possible with: https://developer.amazon.com/public/apis/experience/cloud-drive/content/sdk-ios

**Edit** Currently this issue is blocked because [Amazon didn't give us access to their SDK](https://github.com/cryptomator/cryptomator-ios/issues/8#issuecomment-257395882).

**Comment by overheadhunter** [comment]
Not yet, but we already agreed, that S3 will be the next cloud storage adapter to be implemented in the iOS app.

**Comment by MuscleRumble** [comment]
This is not 100% true. Amazon Cloud Drive isn't the same as S3. But yeah, we've agreed to implement Amazon Cloud Drive for the next minor version 1.2. For S3, we would have to use the [AWS Mobile SDK](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/), which is not the same as the aforementioned [Amazon Drive SDK](https://developer.amazon.com/public/apis/experience/cloud-drive/content/sdk-ios).

**Comment by overheadhunter** [comment]
Can't we use the AWS API to access cloud drive? I assume, that cloud drive is based on S3 anyway.

**Comment by MuscleRumble** [comment]
Nope. Amazon Cloud Drive obviously uses the S3 storage internally, but the API is still different.

**Comment by tobihagemann** [comment]
Just wanted to give a quick update that I'm not sure if we're able to implement Amazon Drive at all (and very unlikely for version 1.2). The [new Amazon Drive SDK](https://developer.amazon.com/cloud-drive) (since August) is only available by invitation. I didn't know that and I've asked for an invitation last week, but haven't heard from them yet.

**Comment by tobihagemann** [comment]
We have some bad news regarding Amazon Drive support.

> Thank you for your interest in using the Amazon Drive developer tools. We consider a variety of factors as we evaluate each invite request, including the use case your application will support. While our goal is to offer a broad and compelling assortment of applications to Amazon Drive customers, we are currently unable to approve your request for access.

I've actually no idea if Amazon has any plans to open up their SDK anytime soon. We're very disappointed with their decision, but that's just how it is at the moment. We'll keep our eyes open!

**Comment by tobihagemann** [comment]
Will re-open this issue once Amazon Drive support is technically possible.

**Comment by patmuk** [comment]
Here is a workaround for the time being:
If you just occasionally need the files on a smartphone - or are willing to pay for the access - then you could go for https://eu.storagemadeeasy.com + Cryptomator iOS/Android app.
storagemadeeasy enables webDAV access for Amazon Drive!
Limitation: the free account allows only a transfer of 150 MB per month.

1. register a free account at https://eu.storagemadeeasy.com/cloud_apps/ (one can choose between US or EU server.
2. grant access to Amazon Drive for the (no concerns if everything is encrypted - though you have to give all-or-nothing access)
3. access the drive via webDAV: https://webdaveu.storagemadeeasy.com (for EU servers) or https://webdav.storagemadeeasy.com (for US servers)
4. access the drive via the smartphone app with the above URL.

Nevertheless, could you maybe again ask Amazon Drive for the API access invite?
Is it any help if one of us tries? Could you use the access if any person get's it?

**Comment by tobihagemann** [comment]
Interesting workaround! Haven't looked at it in detail and isn't something that we can recommend officially, but it's a valid suggestion. :smile:

Hm, about 3 months have passed since the last response. I could try to ask again, but it's very likely that we get declined if nothing has changed.

I've also thought about Cryptomator users asking Amazon as well so that they know there is demand. Not sure if this is something that we should organize though (something like a petition).

As far as I know, the access is tied to an Amazon account, so it shouldn't be an account of "any person". We'd prefer if that account is in our hands. If you'd like to try to request an access, you could tell them that they should contact us via email ([support@cryptomator.org](mailto:support@cryptomator.org)).

**Comment by sachitv** [comment]
Could you try asking again please? It seems like some like folks at Boxcryptor have been able to do this now.

https://www.boxcryptor.com/en/blog/post/boxcryptor-now-supports-amazon-cloud-drive/

**Comment by tobihagemann** [comment]
Yes, I've already sent a request last Tuesday. Last time it took about a month until they responded. Thank you for your hint on Boxcryptor, didn't know about that. If they reject us again, we'll point that out to Amazon.

**Comment by ZiiX** [comment]
let's not forget about minio.io that's growing in popularity as an s3 compatible storage solution. I'd enjoy syncing cryptomator directly to my minio.

**Comment by thedave80** [comment]
Any new on this or something we can do to help? @tobihagemann

**Comment by tobihagemann** [comment]
Unfortunately, no. It's closed for new developers: https://developer.amazon.com/amazon-drive

**Comment by overheadhunter** [comment]
Regarding S3, see #110.
