### ISSUE TITLE
Display full filenames

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptomator-ios#81]
Currently, you aren't able to see the full filenames when they get truncated by ellipsis. You can see the full filename if you rename the file, but that's about it.

### Proposed Solutions
1. Add an advanced option in the settings so that you can deactivate filename truncation. This would mean that file entries (the cells) would have a variable size.
2. Long press on file entry showing the full filename in a `UIMenuItem` (or something similar).
3. In the process of replacing the swipe gestures on file entries (which is scheduled for version 1.3.0), I'd like to show the full filename in the action sheet anyway.

### Comments on Proposed Solutions
1. It's very likely that we'll solve this with an advanced option. I don't think that variable sizes is a good solution, that's why it won't be a default option.
2. Even though it would work, I dislike this solution, because 3D Touch is making long press gestures a lot harder. Not a big fan of gestures nowadays.
3. The question is if this solution is already sufficient.

I've looked into iCloud Drive, Dropbox, Google Drive, and OneDrive. As far as I can see, they all don't have a solution for this. That's quite interesting. Well, some at least have a "detailed" view with the full filename, but this is what I wanted to achieve with solution 3.

**Comment by kapgit** [comment]
Hi,
Thanks for taking the time to formalize my request :)

My need would be to quickly find which file to open in a potentially long list of long filenames, then to select and open it locally or in another app. In my case, filenames are descriptive enough, not to need "real-time" previews, although an occasional quick preview sometimes helps to disambiguate. So, I would suggest:

On iPad/iphone, landscape orientation: leftmost 2/3 to 3/4 column width dedicated to the file list (horizontal scrolling if needed, depending on content width), the remainder would be the preview area for the selected file.

On iPad/iphone, portrait orientation: all width dedicated to the file list (horizontal scrolling if needed, depending on content width). Preview on demand, replacing the file list area.

The idea of an advanced option seems a good one.

**Comment by tobihagemann** [comment]
Fixed in 1.3.0

Swipe gestures have been replaced and full filenames are now shown in the action sheet.
