### ISSUE TITLE
Cryptomator doesn't show up as storage provider in document picker in other apps

### ISSUE THREAD

**Issue by NicolasCGN** [cryptomator/cryptomator-ios#82]
When trying to transfer a file from a Cryptomator vault to other app using the storage extension, Cryptomator does not show up as an option.
![](http://i.imgur.com/OAA9xml.jpg)![](http://i.imgur.com/XtRpzwt.jpg)

Is this planned for the iOSapp?

**Comment by tobihagemann** [comment]
Cryptomator has an import/export document provider extension. Therefore, transferring files to/from Cryptomator should absolutely be possible. Open/move isn't implemented yet, see #13.

Could you give an example of your screenshots? What app did you use and what action did you perform?

**Comment by NicolasCGN** [comment]
The upper screenshot is from Cloud Opener, when selecting in the iCloud view 'Locations' and from the popup menu the option 'More' to add further storage providers.

The lower screenshot comes from Signal (beta version 2.11.0.3) when trying to send a Document to a contact from a storage provider after having selected 'More' in the popup menu of the active storage providers. Is the most intuitive way of sending a document to a contact from a Cryptomator vault through Signal.

The way of copying a Document directly from Cryptomator and then pasting it in Signal works, but it's not the most straightforward way.

**Comment by tobihagemann** [comment]
That's very interesting. Signal can only import `public.data` (kUTTypeData), see [Signal-iOS/MessagesViewController.m#L2195](https://github.com/WhisperSystems/Signal-iOS/blob/a0a930aac330eec3a813016cdcdb3fb9be004d4e/Signal/src/ViewControllers/MessagesViewController.m#L2195). If they added `public.content`, it would've worked. I suppose, Cloud Opener is doing the same.

In our own document provider extension, we've only exposed `public.content` (kUTTypeContent). I have to check why we did that, but I think we can easily fix it by adding `public.data`. I assume, it wasn't intended from us at all to skip `public.data`. Good catch, thank you! Scheduled for the next version 1.2.3.

Reference for UTIs: https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html

**Comment by robsaunders** [comment]
I second this, in most apps I have I can't pick from the Locations document picker at all (documents by readdle, telegram, etc) but some I can (mega). Unfortunately, a huge thing for me would be being able to "import" more than one document, and in the situations the panel does work I have to copy one file at a time. I'm not sure how the document provider extensions work yet so I am not sure if this limitation is insurmountable...?

**Comment by tobihagemann** [comment]
Fixed with 1.2.3

@robsaunders We already support importing multiple documents. But it has to be supported by the "other" app. E.g., if you use Photos, you can select multiple photos and then use Cryptomator's app extension to import them all at once.

But I must totally admit that Cryptomator isn't capable of doing it the other way around, see #52.
