### ISSUE TITLE
PDF viewer re-displaying loop

### ISSUE THREAD

**Issue by Doc-Steve** [cryptomator/cryptomator-ios#85]
## Basic Info

This is a bug report.

I'm using iOS in version: 10.3.1 - iPad Pro 12'

I'm running Cryptomator in version: 1.2.2 436

## Description

For some PDFs the viewer re-displays the current page in a loop, like opening the file over and over. At the end the displaying of the file is aborted with showing an empty page and file name. This seems to happen for PDFs where the thumbnails need a long time to get displayed, e.g. for scanned documents.

I generated a demofile and attached it.
[testdocument_scan.pdf](https://github.com/cryptomator/cryptomator-ios/files/984688/testdocument_scan.pdf)

**Comment by tobihagemann** [comment]
Thank you for your bug report! I can reproduce the issue, thanks to your test file. This is the log output I'm getting while debugging the issue:

```
[default] View service did terminate with error: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "(null)" UserInfo={Message=Service Connection Interrupted} #Remote
```

I'm currently analyzing the issue and looking for a fix. We're using [Quick Look](https://developer.apple.com/ios/human-interface-guidelines/features/quick-look/) to preview files, `[QLPreviewController](https://developer.apple.com/reference/quicklook/qlpreviewcontroller)` in particular. That's why, it's quite possible that it's an upstream bug.

**Comment by tobihagemann** [comment]
I don't know what we can do here. It seems to be an upstream bug, as I've already suspected. The only similar bug report I've found is [this one](http://stackoverflow.com/questions/43616284/quicklook-fails-loading-some-files). I'll file a radar to Apple.

**Comment by tobihagemann** [comment]
Response from Apple:

> We believe this issue is resolved in the latest iOS 11 beta.
> 
> Please test with the latest iOS beta. If you still have issues, please update your bug report with any relevant logs or information that could help us investigate.
> 
> https://developer.apple.com/download/

I must admit that I currently don't have a iOS 11 test device to verify the fix but this sounds promising. :smile:

**Comment by Doc-Steve** [comment]
Thanks, sounds great. I also don't have a test device, but I will test and report with final iOS 11.

**Comment by xhp281** [comment]
I ran into this problem again on iOS 12.0.1, just to show that individual PDF will have this problem. The error information is as follows:
 [default] Preview collection viewServiceDidTerminateWithError: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "(null)" UserInfo={Message=Service Connection Interrupted} #Remote
 [default] View service did terminate with error: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "(null)" UserInfo={Message=Service Connection Interrupted} #Remote
 [default] Preview collection viewServiceDidTerminateWithError: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "(null)" UserInfo={Message=Service Connection Interrupted} #Remote

**Comment by fr33kill** [comment]
@xhp281 - Where you able to overcome this issue?
