### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by chrispatcher** [cryptomator/cryptomator-ios#87]
To tick a checkbox replace [ ] with [x]. Make sure to replace placeholders (…) accordingly.

## Issue Checklist

Before creating a new issue make sure that you
- [ ] searched [existing (and closed) issues](https://github.com/cryptomator/cryptomator-ios/issues).
- [ ] searched the [knowledge base](https://cryptomator.freshdesk.com/support/solutions).
- [ ] have read the [contribution guide](https://github.com/cryptomator/cryptomator-ios/blob/master/CONTRIBUTING.md).
- [ ] have read the [Code of Conduct](https://github.com/cryptomator/cryptomator-ios/blob/master/CODE_OF_CONDUCT.md).

## Basic Info

This is a
- [ ] bug report.
- [ ] feature request.
- [ ] question or something else.

I'm using iOS in version: …

I'm running Cryptomator in version: …  
(You can check the version in the Cryptomator settings under "About Cryptomator".)

## Description

…  
(Please describe in detail what you did, what you expected, and what really happened.)

**Comment by tobihagemann** [comment]
Hi @chrispatcher. Did you accidentally create this issue? Feel free to edit your original post and re-open this issue if you had plans to report something.
