### ISSUE TITLE
Folders Not showing Up after Desktop and iOS Upgrade

### ISSUE THREAD

**Issue by hoveeman** [cryptomator/cryptomator-ios#92]
## Basic Info

This is a bug report.

I'm using iOS in version: 10.3.2

I'm running Cryptomator in version: 1.2.4

## Description

I upgraded my desktop Cryptomator app on Windows 10 and verified my vault was fully synced in Google Drive on their website and upgraded my vault to the new version. I verified the new masterkey.cryptomator keys were updated and uploaded to google drive. I verified all of my folders and files show up on my Windows 10 machine after the upgrade. I updated the iOS app in the app store to 1.2.4, unlocked my vault and only the 1 file I have in my root of my Cryptomator Folder on Google Drive shows up. All of my folders with files are missing in the iOS app. I added another file to the root in Windows and it showed up in the iOS app. I created a new folder that was empty in Windows and it did not show up in the iOS app. I added a file to that folder and it still did not appear.

I removed the vault in the iOS app and re-added the vault and the same experience occurred with only the root files. I updated my other iOS device and the same experience.

Expected Result: All Folders and Files show up in the Cryptomator iOS app.

**Comment by tobihagemann** [comment]
Thank you for your bug report! This is indeed a very unfortunate issue from our side and we noticed the bug right after the 1.2.4 release. Luckily it's just a visibility issue (no data loss) and we've already submitted a hotfix to the App Store yesterday. We're waiting for Apple's review and it looks like that they don't work on weekends. Thank you for your patience!

**Comment by hoveeman** [comment]
Thank you for your quick reply! I didn't fear it was data loss since everything was still on my Windows machine. However, thank you for confirming that it is not data loss.

**Comment by abgit** [comment]
v1.2.5 released to public now.. and folders are back again 👍
